# Generated by Django 3.1.1 on 2020-10-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('FoodId', models.AutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(default='', max_length=400)),
                ('FoodPrice', models.IntegerField(default='')),
                ('RestaurantId', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='overall_sales',
            fields=[
                ('SalseId', models.AutoField(primary_key=True, serialize=False)),
                ('AllDayly_E', models.CharField(default='', max_length=400)),
                ('AllMonthly_E', models.CharField(default='', max_length=400)),
                ('AllYearly_E', models.CharField(default='', max_length=400)),
                ('restaurantId', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NameF', models.CharField(default='', max_length=400)),
                ('NameL', models.CharField(default='', max_length=400)),
                ('Email', models.CharField(default='', max_length=400)),
                ('Password', models.CharField(default='', max_length=400)),
                ('PasswordC', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_sales',
            fields=[
                ('Restaurant_salesId', models.AutoField(primary_key=True, serialize=False)),
                ('Dayly_E', models.CharField(default='', max_length=400)),
                ('Monthly_E', models.CharField(default='', max_length=400)),
                ('Yearly_E', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantData',
            fields=[
                ('RestaurantId', models.AutoField(primary_key=True, serialize=False)),
                ('RestaurantName', models.CharField(default='', max_length=400)),
                ('RestaurantAddress', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantId', models.CharField(default='', max_length=400)),
                ('salseId', models.CharField(default='', max_length=400)),
            ],
        ),
    ]
