# Generated by Django 3.0.5 on 2021-04-06 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Register',
            fields=[
                ('Admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('Admin_NameF', models.CharField(default='', max_length=400)),
                ('Admin_NameL', models.CharField(default='', max_length=400)),
                ('Admin_Email', models.CharField(default='', max_length=400)),
                ('Admin_Password', models.CharField(default='', max_length=400)),
                ('Admin_PasswordC', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('FoodId', models.AutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(default='', max_length=400)),
                ('FoodPrice', models.IntegerField(default='')),
                ('RestaurantId', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='overall_sales',
            fields=[
                ('SalseId', models.AutoField(primary_key=True, serialize=False)),
                ('AllDayly_E', models.CharField(default='', max_length=400)),
                ('AllMonthly_E', models.CharField(default='', max_length=400)),
                ('AllWeekly_E', models.CharField(default='', max_length=400)),
                ('restaurantId', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=300)),
                ('ProductQty', models.CharField(max_length=300)),
                ('ProductPrice', models.CharField(max_length=300)),
                ('QP', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_sales',
            fields=[
                ('Restaurant_salesId', models.AutoField(primary_key=True, serialize=False)),
                ('Dayly_E', models.CharField(default='', max_length=400)),
                ('Monthly_E', models.CharField(default='', max_length=400)),
                ('Weekly_E', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantData',
            fields=[
                ('RestaurantId', models.AutoField(primary_key=True, serialize=False)),
                ('RestaurantName', models.CharField(default='', max_length=400)),
                ('RestaurantAddress', models.CharField(default='', max_length=400)),
                ('ucode', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantId', models.CharField(default='', max_length=400)),
                ('salseId', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_NameF', models.CharField(default='', max_length=400)),
                ('User_NameL', models.CharField(default='', max_length=400)),
                ('User_Email', models.CharField(default='', max_length=400)),
                ('User_Password', models.CharField(default='', max_length=400)),
                ('User_PasswordC', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Ordert',
            fields=[
                ('OId', models.AutoField(primary_key=True, serialize=False)),
                ('ODate', models.DateField(default=django.utils.timezone.now)),
                ('Ino', models.CharField(default='', max_length=50)),
                ('TPrice', models.CharField(default='', max_length=400)),
                ('RestaurantName', models.CharField(default='', max_length=400)),
                ('Allproduct', models.ManyToManyField(to='Restaurant.Product')),
            ],
        ),
    ]
