# Generated by Django 3.1.1 on 2020-10-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OId', models.AutoField(primary_key=True, serialize=False)),
                ('TPrice', models.CharField(default='', max_length=400)),
                ('Allproduct', models.ManyToManyField(to='Restaurant.Product')),
            ],
        ),
    ]
