# Generated by Django 3.1.1 on 2020-10-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_order_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Ordert',
        ),
    ]
