# Generated by Django 3.1.1 on 2020-10-12 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_auto_20201012_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordert',
            name='ODate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
