# Generated by Django 3.1.1 on 2020-10-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0008_product_qp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overall_sales',
            old_name='AllYearly_E',
            new_name='AllWeekly_E',
        ),
        migrations.RenameField(
            model_name='restaurant_sales',
            old_name='Yearly_E',
            new_name='Weekly_E',
        ),
        migrations.AddField(
            model_name='ordert',
            name='RestaurantName',
            field=models.CharField(default='', max_length=400),
        ),
    ]
